front_left_motor:
  type: Motor
  port: 1
  inverted: false
  calibration:
    ticks_to_rad: 0.0033983
    vel_lpf_alpha: 0.05
    bemf_offset: -54.2952
    static_friction_pct: 2
front_right_motor:
  type: Motor
  port: 0
  inverted: true
  calibration:
    ticks_to_rad: 0.00355639
    vel_lpf_alpha: 0.2
    bemf_offset: 32.9275
    static_friction_pct: 2
rear_left_motor:
  type: Motor
  port: 2
  inverted: false
  calibration:
    ticks_to_rad: 0.00365705
    vel_lpf_alpha: 0.05
    bemf_offset: -5.0214
    static_friction_pct: 11
rear_right_motor:
  type: Motor
  port: 3
  inverted: true
  calibration:
    ticks_to_rad: 0.00356289
    vel_lpf_alpha: 0.05
    bemf_offset: -8.1262
    static_friction_pct: 10
